package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1



/**
 * ComprendresbtId generated by hbm2java
 */
public class ComprendresbtId  implements java.io.Serializable {


     private int codesbt;
     private int codept;

    public ComprendresbtId() {
    }

    public ComprendresbtId(int codesbt, int codept) {
       this.codesbt = codesbt;
       this.codept = codept;
    }
   
    public int getCodesbt() {
        return this.codesbt;
    }
    
    public void setCodesbt(int codesbt) {
        this.codesbt = codesbt;
    }
    public int getCodept() {
        return this.codept;
    }
    
    public void setCodept(int codept) {
        this.codept = codept;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ComprendresbtId) ) return false;
		 ComprendresbtId castOther = ( ComprendresbtId ) other; 
         
		 return (this.getCodesbt()==castOther.getCodesbt())
 && (this.getCodept()==castOther.getCodept());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodesbt();
         result = 37 * result + this.getCodept();
         return result;
   }   


}


