package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1



/**
 * Comprendresbt generated by hbm2java
 */
public class Comprendresbt  implements java.io.Serializable {


     private ComprendresbtId id;

    public Comprendresbt() {
    }

    public Comprendresbt(ComprendresbtId id) {
       this.id = id;
    }
   
    public ComprendresbtId getId() {
        return this.id;
    }
    
    public void setId(ComprendresbtId id) {
        this.id = id;
    }




}


