package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1



/**
 * Comprendretype generated by hbm2java
 */
public class Comprendretype  implements java.io.Serializable {


     private ComprendretypeId id;

    public Comprendretype() {
    }

    public Comprendretype(ComprendretypeId id) {
       this.id = id;
    }
   
    public ComprendretypeId getId() {
        return this.id;
    }
    
    public void setId(ComprendretypeId id) {
        this.id = id;
    }




}


