package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1



/**
 * Correspondre generated by hbm2java
 */
public class Correspondre  implements java.io.Serializable {


     private CorrespondreId id;

    public Correspondre() {
    }

    public Correspondre(CorrespondreId id) {
       this.id = id;
    }
   
    public CorrespondreId getId() {
        return this.id;
    }
    
    public void setId(CorrespondreId id) {
        this.id = id;
    }




}


