package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1



/**
 * CorrespondreId generated by hbm2java
 */
public class CorrespondreId  implements java.io.Serializable {


     private int codept;
     private int codeprofil;

    public CorrespondreId() {
    }

    public CorrespondreId(int codept, int codeprofil) {
       this.codept = codept;
       this.codeprofil = codeprofil;
    }
   
    public int getCodept() {
        return this.codept;
    }
    
    public void setCodept(int codept) {
        this.codept = codept;
    }
    public int getCodeprofil() {
        return this.codeprofil;
    }
    
    public void setCodeprofil(int codeprofil) {
        this.codeprofil = codeprofil;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CorrespondreId) ) return false;
		 CorrespondreId castOther = ( CorrespondreId ) other; 
         
		 return (this.getCodept()==castOther.getCodept())
 && (this.getCodeprofil()==castOther.getCodeprofil());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodept();
         result = 37 * result + this.getCodeprofil();
         return result;
   }   


}


