package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1



/**
 * DetenirId generated by hbm2java
 */
public class DetenirId  implements java.io.Serializable {


     private int codeprofil;
     private int codeu;

    public DetenirId() {
    }

    public DetenirId(int codeprofil, int codeu) {
       this.codeprofil = codeprofil;
       this.codeu = codeu;
    }
   
    public int getCodeprofil() {
        return this.codeprofil;
    }
    
    public void setCodeprofil(int codeprofil) {
        this.codeprofil = codeprofil;
    }
    public int getCodeu() {
        return this.codeu;
    }
    
    public void setCodeu(int codeu) {
        this.codeu = codeu;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetenirId) ) return false;
		 DetenirId castOther = ( DetenirId ) other; 
         
		 return (this.getCodeprofil()==castOther.getCodeprofil())
 && (this.getCodeu()==castOther.getCodeu());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodeprofil();
         result = 37 * result + this.getCodeu();
         return result;
   }   


}


