package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1



/**
 * Detenir generated by hbm2java
 */
public class Detenir  implements java.io.Serializable {


     private DetenirId id;

    public Detenir() {
    }

    public Detenir(DetenirId id) {
       this.id = id;
    }
   
    public DetenirId getId() {
        return this.id;
    }
    
    public void setId(DetenirId id) {
        this.id = id;
    }




}


