package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1



/**
 * Exercice generated by hbm2java
 */
public class Exercice  implements java.io.Serializable {


     private Integer codee;
     private String libellee;
     private String objectife;
     private String lienvideo;
     private String desc;
    

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Exercice() {
    }

    public Exercice(String libellee, String objectife, String lienvideo) {
       this.libellee = libellee;
       this.objectife = objectife;
       this.lienvideo = lienvideo;
    }
    public Exercice(Integer id,String libellee, String objectife, String lienvideo) {
       this.codee=id;
       this.libellee = libellee;
       this.objectife = objectife;
       this.lienvideo = lienvideo;
    }

    public Exercice(Integer codee, String libellee, String objectife, String lienvideo, String desc) {
        this.codee = codee;
        this.libellee = libellee;
        this.objectife = objectife;
        this.lienvideo = lienvideo;
        this.desc = desc;
       
    }
   
    public Integer getCodee() {
        return this.codee;
    }
    
    public void setCodee(Integer codee) {
        this.codee = codee;
    }
    public String getLibellee() {
        return this.libellee;
    }
    
    public void setLibellee(String libellee) {
        this.libellee = libellee;
    }
    public String getObjectife() {
        return this.objectife;
    }
    
    public void setObjectife(String objectife) {
        this.objectife = objectife;
    }
    public String getLienvideo() {
        return this.lienvideo;
    }
    
    public void setLienvideo(String lienvideo) {
        this.lienvideo = lienvideo;
    }



}


