package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1



/**
 * Organisertype generated by hbm2java
 */
public class Organisertype  implements java.io.Serializable {


     private OrganisertypeId id;
     private Integer ordrest;
     private Integer seriest;
     private Integer dureeattendue;
     private Integer nbattendu;

    public Organisertype() {
    }

	
    public Organisertype(OrganisertypeId id) {
        this.id = id;
    }
    public Organisertype(OrganisertypeId id, Integer ordrest, Integer seriest, Integer dureeattendue, Integer nbattendu) {
       this.id = id;
       this.ordrest = ordrest;
       this.seriest = seriest;
       this.dureeattendue = dureeattendue;
       this.nbattendu = nbattendu;
    }
   
    public OrganisertypeId getId() {
        return this.id;
    }
    
    public void setId(OrganisertypeId id) {
        this.id = id;
    }
    public Integer getOrdrest() {
        return this.ordrest;
    }
    
    public void setOrdrest(Integer ordrest) {
        this.ordrest = ordrest;
    }
    public Integer getSeriest() {
        return this.seriest;
    }
    
    public void setSeriest(Integer seriest) {
        this.seriest = seriest;
    }
    public Integer getDureeattendue() {
        return this.dureeattendue;
    }
    
    public void setDureeattendue(Integer dureeattendue) {
        this.dureeattendue = dureeattendue;
    }
    public Integer getNbattendu() {
        return this.nbattendu;
    }
    
    public void setNbattendu(Integer nbattendu) {
        this.nbattendu = nbattendu;
    }




}


