package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1



/**
 * OrganisertypeId generated by hbm2java
 */
public class OrganisertypeId  implements java.io.Serializable {


     private int codee;
     private int codest;

    public OrganisertypeId() {
    }

    public OrganisertypeId(int codee, int codest) {
       this.codee = codee;
       this.codest = codest;
    }
   
    public int getCodee() {
        return this.codee;
    }
    
    public void setCodee(int codee) {
        this.codee = codee;
    }
    public int getCodest() {
        return this.codest;
    }
    
    public void setCodest(int codest) {
        this.codest = codest;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrganisertypeId) ) return false;
		 OrganisertypeId castOther = ( OrganisertypeId ) other; 
         
		 return (this.getCodee()==castOther.getCodee())
 && (this.getCodest()==castOther.getCodest());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodee();
         result = 37 * result + this.getCodest();
         return result;
   }   


}


