package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1

import java.sql.Date;




/**
 * Planifierbilan generated by hbm2java
 */
public class Planifierbilan  implements java.io.Serializable {


     private PlanifierbilanId id;
     private Integer ordreb;
     private Integer nbmaxu;
     private Integer tempsmaxu;
     private Date dater;

   

    public Planifierbilan() {
    }

	
    public Planifierbilan(PlanifierbilanId id) {
        this.id = id;
    }
    public Planifierbilan(PlanifierbilanId id, Date date,Integer ordreb, Integer nbmaxu, Integer tempsmaxu) {
        this.dater=date;
       this.id = id;
       this.ordreb = ordreb;
       this.nbmaxu = nbmaxu;
       this.tempsmaxu = tempsmaxu;
    }
   
    public PlanifierbilanId getId() {
        return this.id;
    }
    
    public void setId(PlanifierbilanId id) {
        this.id = id;
    }
    public Integer getOrdreb() {
        return this.ordreb;
    }
    
    public void setOrdreb(Integer ordreb) {
        this.ordreb = ordreb;
    }
    public Integer getNbmaxu() {
        return this.nbmaxu;
    }
    
    public void setNbmaxu(Integer nbmaxu) {
        this.nbmaxu = nbmaxu;
    }
    public Integer getTempsmaxu() {
        return this.tempsmaxu;
    }
    
    public void setTempsmaxu(Integer tempsmaxu) {
        this.tempsmaxu = tempsmaxu;
    }

 public Date getDater() {
        return dater;
    }

    public void setDater(Date dater) {
        this.dater = dater;
    }

}


