package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PlanifierbilanId generated by hbm2java
 */
public class PlanifierbilanId  implements java.io.Serializable {


     private int codesb;
     private int codee;
     private Date dater;

    public PlanifierbilanId() {
    }

    public PlanifierbilanId(int codesb, int codee, Date dater) {
       this.codesb = codesb;
       this.codee = codee;
       this.dater = dater;
    }
   
    public int getCodesb() {
        return this.codesb;
    }
    
    public void setCodesb(int codesb) {
        this.codesb = codesb;
    }
    public int getCodee() {
        return this.codee;
    }
    
    public void setCodee(int codee) {
        this.codee = codee;
    }
    public Date getDater() {
        return this.dater;
    }
    
    public void setDater(Date dater) {
        this.dater = dater;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlanifierbilanId) ) return false;
		 PlanifierbilanId castOther = ( PlanifierbilanId ) other; 
         
		 return (this.getCodesb()==castOther.getCodesb())
 && (this.getCodee()==castOther.getCodee())
 && ( (this.getDater()==castOther.getDater()) || ( this.getDater()!=null && castOther.getDater()!=null && this.getDater().equals(castOther.getDater()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodesb();
         result = 37 * result + this.getCodee();
         result = 37 * result + ( getDater() == null ? 0 : this.getDater().hashCode() );
         return result;
   }   


}


