package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PlanifierspId generated by hbm2java
 */
public class PlanifierspId  implements java.io.Serializable {


     private int codesp;
     private int codee;
     private Date dater;

    public PlanifierspId() {
    }

    public PlanifierspId(int codesp, int codee, Date dater) {
       this.codesp = codesp;
       this.codee = codee;
       this.dater = dater;
    }
   
    public int getCodesp() {
        return this.codesp;
    }
    
    public void setCodesp(int codesp) {
        this.codesp = codesp;
    }
    public int getCodee() {
        return this.codee;
    }
    
    public void setCodee(int codee) {
        this.codee = codee;
    }
    public Date getDater() {
        return this.dater;
    }
    
    public void setDater(Date dater) {
        this.dater = dater;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlanifierspId) ) return false;
		 PlanifierspId castOther = ( PlanifierspId ) other; 
         
		 return (this.getCodesp()==castOther.getCodesp())
 && (this.getCodee()==castOther.getCodee())
 && ( (this.getDater()==castOther.getDater()) || ( this.getDater()!=null && castOther.getDater()!=null && this.getDater().equals(castOther.getDater()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodesp();
         result = 37 * result + this.getCodee();
         result = 37 * result + ( getDater() == null ? 0 : this.getDater().hashCode() );
         return result;
   }   


}


