package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1



/**
 * Planifiersp generated by hbm2java
 */
public class Planifiersp  implements java.io.Serializable {


     private PlanifierspId id;
     private Integer ordrep;
     private Integer nbattendue;
     private Integer dureeattenduee;
     private Integer tempsrepose;
     private int seriep;
     private String resultatu;

    public Planifiersp() {
    }

	
    public Planifiersp(PlanifierspId id) {
        this.id = id;
    }
    public Planifiersp(PlanifierspId id, Integer ordrep, Integer nbattendue, Integer dureeattenduee, Integer tempsrepose, Integer seriep, String resultatu) {
       this.id = id;
       this.ordrep = ordrep;
       this.nbattendue = nbattendue;
       this.dureeattenduee = dureeattenduee;
       this.tempsrepose = tempsrepose;
       this.seriep = seriep;
       this.resultatu = resultatu;
    }

    public Planifiersp(Integer ordrep, Integer nbattendue, Integer dureeattenduee, Integer tempsrepose, Integer seriep, String resultatu) {
        this.ordrep = ordrep;
        this.nbattendue = nbattendue;
        this.dureeattenduee = dureeattenduee;
        this.tempsrepose = tempsrepose;
        this.seriep = seriep;
        this.resultatu = resultatu;
    }
   
    public PlanifierspId getId() {
        return this.id;
    }
    
    public void setId(PlanifierspId id) {
        this.id = id;
    }
    public Integer getOrdrep() {
        return this.ordrep;
    }
    
    public void setOrdrep(Integer ordrep) {
        this.ordrep = ordrep;
    }
    public Integer getNbattendue() {
        return this.nbattendue;
    }
    
    public void setNbattendue(Integer nbattendue) {
        this.nbattendue = nbattendue;
    }
    public Integer getDureeattenduee() {
        return this.dureeattenduee;
    }
    
    public void setDureeattenduee(Integer dureeattenduee) {
        this.dureeattenduee = dureeattenduee;
    }
    public Integer getTempsrepose() {
        return this.tempsrepose;
    }
    
    public void setTempsrepose(Integer tempsrepose) {
        this.tempsrepose = tempsrepose;
    }
    public int getSeriep() {
        return this.seriep;
    }
    
    public void setSeriep(int seriep) {
        this.seriep = seriep;
    }
    public String getResultatu() {
        return this.resultatu;
    }
    
    public void setResultatu(String resultatu) {
        this.resultatu = resultatu;
    }




}


