package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1

/**
 * Programmeperso generated by hbm2java
 */
public class Programmeperso implements java.io.Serializable {

    private Integer codepp;
    private int codeu;
    private int codept;
    private String libellepp;
    private String descriptionpp;

    public Programmeperso() {
    }

    public Programmeperso(int codeu, int codept) {
        this.codeu = codeu;
        this.codept = codept;
    }

    public Programmeperso(int codeu, int codept, String libellepp, String descriptionpp) {
        this.codeu = codeu;
        this.codept = codept;
        this.libellepp = libellepp;
        this.descriptionpp = descriptionpp;
    }

    public Programmeperso(int codepp, int codeu, int codept, String libellepp, String descriptionpp) {
        this.codepp = codepp;
        this.codeu = codeu;
        this.codept = codept;
        this.libellepp = libellepp;
        this.descriptionpp = descriptionpp;
    }

    public Integer getCodepp() {
        return this.codepp;
    }

    public void setCodepp(Integer codepp) {
        this.codepp = codepp;
    }

    public int getCodeu() {
        return this.codeu;
    }

    public void setCodeu(int codeu) {
        this.codeu = codeu;
    }

    public int getCodept() {
        return this.codept;
    }

    public void setCodept(int codept) {
        this.codept = codept;
    }

    public String getLibellepp() {
        return this.libellepp;
    }

    public void setLibellepp(String libellepp) {
        this.libellepp = libellepp;
    }

    public String getDescriptionpp() {
        return this.descriptionpp;
    }

    public void setDescriptionpp(String descriptionpp) {
        this.descriptionpp = descriptionpp;
    }

}
