package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1



/**
 * Seancebilantype generated by hbm2java
 */
public class Seancebilantype  implements java.io.Serializable {


     private Integer codesbt;
     private String libellesbt;
     private String descriptionsbt;

    public Seancebilantype() {
    }

    public Seancebilantype(Integer codesbt,String libellesbt, String descriptionsbt) { this.codesbt=codesbt;
       this.libellesbt = libellesbt;
       this.descriptionsbt = descriptionsbt;
    }
   
    public Integer getCodesbt() {
        return this.codesbt;
    }
    
    public void setCodesbt(Integer codesbt) {
        this.codesbt = codesbt;
    }
    public String getLibellesbt() {
        return this.libellesbt;
    }
    
    public void setLibellesbt(String libellesbt) {
        this.libellesbt = libellesbt;
    }
    public String getDescriptionsbt() {
        return this.descriptionsbt;
    }
    
    public void setDescriptionsbt(String descriptionsbt) {
        this.descriptionsbt = descriptionsbt;
    }




}


