package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1

import java.sql.Date;

/**
 * Seancebilan generated by hbm2java
 */

public class Seancebilan  implements java.io.Serializable {


     private Integer codesb;
     private int codesbt;
     private int codepp;
     private String libellesb;
     private String numsemaine;
     private String commentairecoach;
     private String etatlucoach;
     private String ouvert;
     private String validersb;
    private String fcRepos;
    private String fcMax;
    private String fcFlexion;
    private String fcRecup;
    private String dateM;

    public Seancebilan() {
    }


    public String getFcRepos() {
        return fcRepos;
    }

    public void setFcRepos(String fcRepos) {
        this.fcRepos = fcRepos;
    }

    public String getFcMax() {
        return fcMax;
    }

    public void setFcMax(String fcMax) {
        this.fcMax = fcMax;
    }

    public String getFcFlexion() {
        return fcFlexion;
    }

    public void setFcFlexion(String fcFlexion) {
        this.fcFlexion = fcFlexion;
    }

    public String getFcRecup() {
        return fcRecup;
    }

    public void setFcRecup(String fcRecup) {
        this.fcRecup = fcRecup;
    }

    public String getDateM() {
        return dateM;
    }

    public void setDateM(String dateM) {
        this.dateM = dateM;
    }


    public Seancebilan(int codesbt, int codepp) {
        this.codesbt = codesbt;
        this.codepp = codepp;
    }

    public Seancebilan(int codesbt, int codepp, String libellesb, String numsemaine, String commentairecoach, String etatlucoach, String ouvert, String validersb) {
        this.codesbt = codesbt;
        this.codepp = codepp;
        this.libellesb = libellesb;
        this.numsemaine = numsemaine;
        this.commentairecoach = commentairecoach;
        this.etatlucoach = etatlucoach;
        this.ouvert = ouvert;
        this.validersb = validersb;
    }




    public Seancebilan(int codesb, String nom, String semaine, String com, String lu, String ouvert, String validerSb, String fcRepos, String fcMax, String fcFlexion, String fcRecup, String dateM) {
        this.codesb = codesb;
        this.libellesb = nom;
        this.numsemaine = semaine;
        this.commentairecoach = com;
        this.etatlucoach = lu;
        this.ouvert = ouvert;
        this.validersb = validerSb;
        this.fcRepos = fcRepos;
        this.fcMax = fcMax;
        this.fcFlexion = fcFlexion;
        this.fcRecup = fcRecup;
        this.dateM = dateM;
    }

    public Integer getCodesb() {
        return this.codesb;
    }

    public void setCodesb(Integer codesb) {
        this.codesb = codesb;
    }

    public int getCodesbt() {
        return this.codesbt;
    }

    public void setCodesbt(int codesbt) {
        this.codesbt = codesbt;
    }

    public int getCodepp() {
        return this.codepp;
    }

    public void setCodepp(int codepp) {
        this.codepp = codepp;
    }

    public String getLibellesb() {
        return this.libellesb;
    }

    public void setLibellesb(String libellesb) {
        this.libellesb = libellesb;
    }

    public String getNumsemaine() {
        return this.numsemaine;
    }

    public void setNumsemaine(String numsemaine) {
        this.numsemaine = numsemaine;
    }

    public String getCommentairecoach() {
        return this.commentairecoach;
    }

    public void setCommentairecoach(String commentairecoach) {
        this.commentairecoach = commentairecoach;
    }

    public String getEtatlucoach() {
        return this.etatlucoach;
    }

    public void setEtatlucoach(String etatlucoach) {
        this.etatlucoach = etatlucoach;
    }

    public String getOuvert() {
        return this.ouvert;
    }

    public void setOuvert(String ouvert) {
        this.ouvert = ouvert;
    }

    public String getValidersb() {
        return this.validersb;
    }

    public void setValidersb(String validersb) {
        this.validersb = validersb;
    }

}
