package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1



/**
 * Seanceperso generated by hbm2java
 */
public class Seanceperso  implements java.io.Serializable {


     private Integer codesp;
     private int codepp;
     private int codest;
     private String libellesp;
     private String descriptionsp;
     private String commentairecoach;
     private Integer nbrepetitions;
     private Integer numsemaine;
     private String etatlucoach;
     private String ouvert;
     private String validersp;
    private String echauffementst;
    private String orderSp;
    private int codecat;
    public Seanceperso() {
    }

    public String getOrderSp() {
        return orderSp;
    }

    public void setOrderSp(String orderSp) {
        this.orderSp = orderSp;
    }

    public int getCodecat() {
        return codecat;
    }

    public void setCodecat(int codecat) {
        this.codecat = codecat;
    }

    public String getEchauffementst() {
        return echauffementst;
    }

    public void setEchauffementst(String echauffementst) {
        this.echauffementst = echauffementst;
    }

    public Seanceperso(int codepp, int codest) {
        this.codepp = codepp;
        this.codest = codest;
    }
    public Seanceperso(int codesp,int codepp, int codest, String libellesp, String descriptionsp, String commentairecoach, Integer nbrepetitions, Integer numsemaine, String etatlucoach, String ouvert, String validersp,String echauffementst,String orderSp,int codecat) {
       this.codesp=codesp;
        this.codepp = codepp;
       this.codest = codest;
       this.libellesp = libellesp;
       this.descriptionsp = descriptionsp;
       this.commentairecoach = commentairecoach;
       this.nbrepetitions = nbrepetitions;
       this.numsemaine = numsemaine;
       this.etatlucoach = etatlucoach;
       this.ouvert = ouvert;
       this.validersp = validersp;
       this.echauffementst=echauffementst;
       this.orderSp=orderSp;
       this.codecat=codecat;
    }

   
    public Integer getCodesp() {
        return this.codesp;
    }
    
    public void setCodesp(Integer codesp) {
        this.codesp = codesp;
    }
    public int getCodepp() {
        return this.codepp;
    }
    
    public void setCodepp(int codepp) {
        this.codepp = codepp;
    }
    public int getCodest() {
        return this.codest;
    }
    
    public void setCodest(int codest) {
        this.codest = codest;
    }
    public String getLibellesp() {
        return this.libellesp;
    }
    
    public void setLibellesp(String libellesp) {
        this.libellesp = libellesp;
    }
    public String getDescriptionsp() {
        return this.descriptionsp;
    }
    
    public void setDescriptionsp(String descriptionsp) {
        this.descriptionsp = descriptionsp;
    }
    public String getCommentairecoach() {
        return this.commentairecoach;
    }
    
    public void setCommentairecoach(String commentairecoach) {
        this.commentairecoach = commentairecoach;
    }
    public Integer getNbrepetitions() {
        return this.nbrepetitions;
    }
    
    public void setNbrepetitions(Integer nbrepetitions) {
        this.nbrepetitions = nbrepetitions;
    }
    public Integer getNumsemaine() {
        return this.numsemaine;
    }
    
    public void setNumsemaine(Integer numsemaine) {
        this.numsemaine = numsemaine;
    }
    public String getEtatlucoach() {
        return this.etatlucoach;
    }
    
    public void setEtatlucoach(String etatlucoach) {
        this.etatlucoach = etatlucoach;
    }
    public String getOuvert() {
        return this.ouvert;
    }
    
    public void setOuvert(String ouvert) {
        this.ouvert = ouvert;
    }
    public String getValidersp() {
        return this.validersp;
    }
    
    public void setValidersp(String validersp) {
        this.validersp = validersp;
    }




}


